freebsd_instance:
  image_family: freebsd-13-0

task:
  configure_repos_script:
    - mkdir -p /usr/local/etc/pkg/repos/
    - >-
      echo $'FreeBSD: {\n\turl: "pkg+http://pkg.FreeBSD.org/${ABI}/latest"\n}' > /usr/local/etc/pkg/repos/FreeBSD.conf
  install_deps_script:
    - pkg upgrade -y
    - pkg install -y elixir
  # install_script: pkg install -y elixir
  # echo_script: echo "hello world"
