freebsd_instance:
  image_family: freebsd-13-0

task:
  install_packages_script:
    - mkdir -p /usr/local/etc/pkg/repos/
    - >-
      echo $'FreeBSD: {\n\turl: "pkg+http://pkg.FreeBSD.org/${ABI}/latest"\n}' > /usr/local/etc/pkg/repos/FreeBSD.conf
    - pkg upgrade -y
    - pkg install -y elixir
    - mix local.hex --force
  test_script: make test
  package_script: make package
