freebsd_instance:
  image_family: freebsd-13-0

task:
  upgrade_packages_script:
    - mkdir -p /usr/local/etc/pkg/repos/
    - >-
      echo $'FreeBSD: {\n\turl: "pkg+http://pkg.FreeBSD.org/${ABI}/latest"\n}' > /usr/local/etc/pkg/repos/FreeBSD.conf
    - pkg upgrade -y
  install_elixir_script:
    - pkg install -y elixir
    - mix local.hex --force
  install_postgres_script:
    - pkg install -y postgresql12-server
    - sysrc postgresql_enable=yes
    - /usr/local/etc/rc.d/postgresql initdb
    - /usr/local/etc/rc.d/postgresql start
    - /usr/local/etc/rc.d/postgresql status
  test_script: make test
  package_script: make package
  test_package_script:
    - pkg add *.pkg
    - ls -l /usr/local/bin/ex_ample
    - /usr/local/bin/ex_ample eval 'IO.puts("hello absolute path")'
    - ex_ample eval 'IO.puts("hello global path")'
  pkg_artifacts:
    path: "*.pkg"
