freebsd_instance:
  image_family: freebsd-13-0

task:
  list_repos_script: ls -a /usr/local/etc/pkg/repos/
  cat_repos_script: cat /usr/local/etc/pkg/repos/FreeBSD.conf
  # install_script: pkg install -y elixir
  # echo_script: echo "hello world"
