freebsd_instance:
  image_family: freebsd-13-0

task:
  upgrade_packages_script:
    - mkdir -p /usr/local/etc/pkg/repos/
    - >-
      echo $'FreeBSD: {\n\turl: "pkg+http://pkg.FreeBSD.org/${ABI}/latest"\n}' > /usr/local/etc/pkg/repos/FreeBSD.conf
    - pkg upgrade -y
  install_elixir_script:
    - pkg install -y elixir
    - mix local.hex --force
    - mix local.rebar --force
  install_postgres_script:
    - pkg install -y postgresql12-server
    - sysrc postgresql_enable=yes
    - /usr/local/etc/rc.d/postgresql initdb
  start_postgres_background_script:
    - /usr/local/etc/rc.d/postgresql start
  test_script: make test
  package_script: make package
  test_package_script:
    - pkg add *.pkg
    - /usr/local/bin/ex_ample version
  pkg_artifacts:
    path: "*.pkg"
