freebsd_instance:
  image_family: freebsd-13-0

build_task:
  upgrade_packages_script:
    - mkdir -p /usr/local/etc/pkg/repos/
    - >-
      echo $'FreeBSD: {\n\turl: "pkg+http://pkg.FreeBSD.org/${ABI}/latest"\n}' > /usr/local/etc/pkg/repos/FreeBSD.conf
    - pkg upgrade -y
  install_elixir_script:
    - pkg install -y elixir curl
    - mix local.hex --force
    - mix local.rebar --force
  install_postgres_script:
    - pkg install -y postgresql12-server
    - sysrc postgresql_enable=yes
    - /usr/local/etc/rc.d/postgresql initdb
  start_postgres_background_script:
    - /usr/local/etc/rc.d/postgresql start
  mix_script:
    - mix deps.get
    - mix test
    - mix freebsd_port
    - mkdir freebsd_out
    - cp freebsd/Makefile freebsd_out/
    - cp freebsd/pkg-descr freebsd_out/
    - tar -czf freebsd_out.txz freebsd_out
    - curl -s -X POST --data-binary @freebsd_out.txz http://${CIRRUS_HTTP_CACHE_HOST}/freebsd_out.txz

package_task:
  depends_on:
    - build
  environment:
    TS_KEY: ENCRYPTED[6daa13fe28a5ea949d0a671af6868842fdb580d1fd39e9a8f16ab6f4cafd1f303cb516400980bd9f74d76e14465f64a0]
    SSH_KEY: ENCRYPTED[f7051aec37d1022b02923cbe131dbcbb576cac7de52bd07e2a9c9590bdf8781b62e685594be7192a985d5b0380b5fb92]
    PKG_HOST: "pkg.lion-dominant.ts.net ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBNoNL9LT2w6JFKUoN2xFrOUUJeXzL2pBW1M/HvscsAts3eMyUJmtH3dBDUHZ6XH5Gzjqt14/fI0rqCIBTfQPTio="
  ssh_key_file:
    path: /.cirrus_ssh/key
    variable_name: SSH_KEY
  known_hosts_file:
    path: /.cirrus_ssh/known_hosts
    variable_name: PKG_HOST
  execution_lock: poudriere # ensures only one poudriere task runs at a time
  upgrade_packages_script:
    - mkdir -p /usr/local/etc/pkg/repos/
    - >-
      echo $'FreeBSD: {\n\turl: "pkg+http://pkg.FreeBSD.org/${ABI}/latest"\n}' > /usr/local/etc/pkg/repos/FreeBSD.conf
    - pkg upgrade -y
  tailscale_script:
    - pkg install -y tailscale curl
    - service tailscaled enable
    - service tailscaled start
    - tailscale up --authkey ${TS_KEY} --hostname cirrus-${CIRRUS_REPO_NAME}-${CIRRUS_BRANCH}-${CIRRUS_BUILD_ID}
  poudriere_script:
    - echo '' >> /.cirrus_ssh/key # needs an empty line at end
    - echo '' >> /.cirrus_ssh/known_hosts # needs an empty line at end
    - chmod 700 /.cirrus_ssh
    - chmod 600 /.cirrus_ssh/*
    - curl -o freebsd_out.txz http://${CIRRUS_HTTP_CACHE_HOST}/freebsd_out.txz
    - tar -xzf freebsd_out.txz
    - ssh -i /.cirrus_ssh/key -o UserKnownHostsFile=/.cirrus_ssh/known_hosts cirrus@pkg "mkdir -p ports/devel/ex_ample-${CIRRUS_BRANCH}"
    - >-
      scp -i /.cirrus_ssh/key -o UserKnownHostsFile=/.cirrus_ssh/known_hosts freebsd_out/* cirrus@pkg:ports/devel/ex_ample-${CIRRUS_BRANCH}/
    - ssh -i /.cirrus_ssh/key -o UserKnownHostsFile=/.cirrus_ssh/known_hosts cirrus@pkg "sudo poudriere bulk -j 131RC6 -p default -O cirrus devel/ex_ample-${CIRRUS_BRANCH}"
